# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: reservations_api_development
  username: postgres
  password: jhon1234

test:
  <<: *default
  database: reservations_api_test
  username: postgres
  password: jhon1234

production:
  <<: *default
  database: reservations_api_production
  username: reservations_api
  password: <%= ENV['RESERVATIONS_API_DATABASE_PASSWORD'] %>
